### ISSUE TITLE
Finalize mocks

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/buildabudget#1]
Starting with Grace, then me, and now Vickie, we've iterated on user flows and wireframes for a bit.

Most of this back and forth on the [Slack channel](https://open-austin.slack.com/messages/hackthebudget/).

Would like to finalize some aspects of what we have and chat IRL so we can comfortably start coding it out.

**Comment by mateoclarke** [comment]
Think we got to a good place with discussing mocks. I have photos of the hand drawn sketches. @VictoriaODell, were you going to do anything further with those?

Also linking to the Duolingo inspired wireframes.
https://wireframe.cc/pro/pp/005cefd3a49876

![img_3190](https://cloud.githubusercontent.com/assets/5697474/16858330/cf6cf3bc-49eb-11e6-920d-901b12994819.JPG)

![img_3191](https://cloud.githubusercontent.com/assets/5697474/16858325/ca9f4e02-49eb-11e6-9d9f-159edbed6a9a.JPG)

**Comment by VictoriaODell** [comment]
Yo!
I sketched out the ideas a bit more and took some more notes the other night. Just trying to understand the flow a little better. I'd like to digitize them. The page I'm struggling a bit on is the report page. While users can go back and change their answers we still need to show some hierarchy. The constant menu we thought of suggests more lateral movement than rather than getting from point A-B and I think that's what makes the reports page a little weird. 

Also, I think on the "Drill down" pages we should ger rid of the constant menu we decided on and replace it with one main "call to action" like "done","submit", still spinning on that( and the menu in general). I want the user to know that once they finish this section they can always come back and change their answer. The reason to break away from the constant menu on this page is because it is more focused/task-oriented? than the other pages and it's a UI pattern that seems common. 

 Language for the content is still something I'm thinking a lot about. 

Also idk why the photos came out sideways. click on them and they are the right side up. 

Hope that made some sort of sense~ If not maybe a Google hangout or call. 
![img_2095](https://cloud.githubusercontent.com/assets/10767430/16858418/454dbc06-49ec-11e6-8dcb-49e84bd967f1.JPG)
![img_2096](https://cloud.githubusercontent.com/assets/10767430/16858417/454d7a20-49ec-11e6-8f87-1966e2b9adb7.JPG)


I

**Comment by VictoriaODell** [comment]
Ok! I think I got it figured out. 
I'm working on making some nicer digital mocks. We could use some copy help. 
I have an idea of the text we put in the mocks but just generally.

**Comment by VictoriaODell** [comment]
[HacktheBudget.pdf](https://github.com/open-austin/hack-the-budget/files/367587/HacktheBudget.pdf)

Sketch Wireframes. 
The color blue 🔵  = an interactive element. 
Overall could use a lot of copy help.

### Page 1 / Home Page
- Button links to Services page where people would begin
- Link under button links to an about page
- Blurb under title could use some copy love

### Page 2 / Services Page
- Top menu is persistent and adjusts as they adjust service spending and revenue  
- Top menu should start with current or default $. Zeros are just placeholders
- Blurb under title needs some copy love
-  Blue circles would be icons or imagery to rep the section 
- Blue circles are clickable and would open up into "drill down page" that would have more info about that service and would allow users to adjust the spending. 
- Bottom menu is persistent and would allow the user to jump around sections if they decide to adjust their answer or want to check out what the rest of the process looks like
- Current page would not be an active link on the bottom menu. 
- People can jump around in the sections.

### Page 3/ Revenue Page
Same as above! 

### Page 4 / Drill down page
- Top menu is persistent and adjusts as they adjust service spending  
- Number under menu denotes how far along they are. In this example they are on 12 of 12. 
- Blurb under title needs some copy love. It should give an overview of the services and what id does. 
- Clicking "read more" would reveal more(Page 5) information(maybe stats) to help guide their decision. 
- Done would be at the bottom of the text they read and is how they can submit their changes. (Wondering if we need a close or back button too? )
- Bottom slider would be persistent and would allow them to toggle spending. As they toggle the spending the $ amount above the slider would adjust

### Page 5 / Report page
-  Services and Revenue section would give a quick overview of the changes they made. Needs lots of copy love. 
- "Overview" text would link to detailed pages shown on page 5. 
- Optional email allows them to send a copy of the the budget to themselves that includes the info on page 6. We can also maybe send a survey or something to if want to collect more info or get feedback on the app
- Submit button would send the budget to whoever it's supposed to go to lol

### Page 5 / Detailed page of changes 
-  Would give a section by section overview of the changes they made and what they mean
- Needs tons of copy love here too
- Menu up top would be persistent and allow them to do 2 things. Go back to the services page and adjust their answers or close the overview page and go back to page 5.

**Comment by VictoriaODell** [comment]
I made an invision prototype really quick too: 
https://invis.io/AY7ZDBSEM#/174484674_HacktheBudget-pdf_1

I realized some of my styling isn't all the way consistent and I need to do som language updates on the menu + menu sections since it doesn't correlate all the way right now. I turned on commenting so it would be great if ya'll could leave feedback or post questions there if possible.

**Comment by VictoriaODell** [comment]
You can also check out the prototype on your phone
<img width="352" alt="screen shot 2016-07-16 at 7 22 32 pm" src="https://cloud.githubusercontent.com/assets/10767430/16897964/ca042486-4b8a-11e6-8ef6-6bc4169d3915.png">

**Comment by VictoriaODell** [comment]
Updated Mocks. 
Still ideating on the reports pages. I only did 1 Service page but the styling should be the same for all of them. 
[HacktheBudget_v3.pdf](https://github.com/open-austin/hack-the-budget/files/380781/HacktheBudget_v3.pdf)

**Comment by VictoriaODell** [comment]
Not much changed. Just added a "Surplus card" We are ideating on the text for issue #24 
[HacktheBudget_v4.pdf](https://github.com/open-austin/hack-the-budget/files/405072/HacktheBudget_v4.pdf)

Didn't update the "fund" page since what Mateo has now seems sufficient

**Comment by VictoriaODell** [comment]
These should be most up to date. I skipped the Fund page since @mateoclarke already has something nice coded.
