### ISSUE TITLE
Replace placeholder blue icons for Report Icons

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/buildabudget#35]
We need to drop in saveAndSubmit.svg & yourBudget.svg into their places on the Report page.

Punted on this for tonight bc I couldn't resize the SVGs nicely as `<img>` tags. It also seems like inline svgs would be good, and I found this [CSS-Tricks article](https://css-tricks.com/creating-svg-icon-system-react/), but that involved some setup.

@VictoriaODell, would it be quick for you to convert the SVG to `.gif` the way you did with the service icons? Is there a good reason to stick with `.gif` over `.svg`?

**Comment by VictoriaODell** [comment]
![saveandsubmit](https://cloud.githubusercontent.com/assets/10767430/17644814/22b1d1dc-6157-11e6-8f5f-894260e989cb.gif)
![yourbudget](https://cloud.githubusercontent.com/assets/10767430/17644815/2729b98c-6157-11e6-8b0a-436900cbd3ce.gif)


I think for now the gifs are fine but it would be nice if we could put everything as an svg in the future. It'll scale better. 

I think you might have had problems with those two icons since they had extra white space to the left of them in the file.
